
## Todoist
todoist_api_payload: ""
todoist_api_token: ""

## Spotify
spotify_client_id: ""
spotify_client_secret: ""

## DNS Update
k-p_v_user: ""
k-p_v_pass: ""

## Proxy 
proxy_ip: ""

## SSH
ssh_pswd: ""

## Samba
samba_user: ""
samba_pass: ""

## MariaDB
mariadb_database1: ""
mariadb_user: ""
mariadb_pass: ""

## GitHub
git_pass: ""

## Pirate Weather
pirate_weather_api: ""
pirate_rest_resource: ""

## Google
google_client: ""
google_secret: ""

# p_lat: ""
# p_long: ""

## MQTT
mqtt_u: ""
mqtt_p: ""

