- platform: mqtt # "video-rack-humidity"
  state_topic: "VideoRacks/Enviros"
  value_template: "{{ value_json.humidity }}"
  name: "video-rack-humidity"
  unit_of_measurement: '%'
  icon: "mdi:water-percent"
  
- platform: mqtt # "video-rack-pressure"
  state_topic: "VideoRacks/Enviros"
  value_template: "{{ value_json.pressure }}"
  name: "video-rack-pressure"
  unit_of_measurement: 'hPa'
  icon: "mdi:arrow-down-bold"

- platform: mqtt # "video-rack-temperature"
  state_topic: "VideoRacks/Enviros"
  value_template: "{{ value_json.temperature }}"
  name: "video-rack-temperature"
  unit_of_measurement: 'F'
  icon: "mdi:thermometer"
  
- platform: mqtt # "video-rack-lux"
  state_topic: "VideoRacks/Enviros"
  value_template: "{{ value_json.lux }}"
  name: "video-rack-lux"
  unit_of_measurement: 'lx'
  icon: "mdi:weather-sunny"
  
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 10
  
- platform: rest #Shit to Get Done List (Video)
  name: Shit to Get Done
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2291585133
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30

- platform: command_line # Tristan's DateTime
  name: Tristans DateTime
  command: >-
    python3 t-tz.py "{{ state_attr('sensor.tristans_s21_current_time_zone', 'time_zone_id') }}"
  value_template: "{{ value_json.datetime }}"
  json_attributes:
    - timezone

# - platform: rest
#   name: PW_test
#   scan_interval: 15
#   resource: !secret pirate_rest_resource
#   value_template: "{{ float(value_json.daily.data.0.precipAccumulation) }}"
#   unit_of_measurement: "cm"
  
# - platform: pirateweather
#   api_key: !secret pirate_weather_api
#   scan_interval: '00:15:00'
#   monitored_conditions:
#     - temperature
#     - precip_probability
#     - precip_type
#     - humidity
#     - cloud_cover
#     - nearest_storm_distance
#     - precip_intensity
#     - wind_speed

- platform: rest
  resource_template: !secret pirate_rest_resource
  json_attributes_path: "$.currently"
  scan_interval: '00:15:00'
  json_attributes:
    - summary
    - temperature
    - precipProbability
    - precipType
    - humidity
    - cloudCover
    - nearestStormDistance
    - precipIntensity
    - windSpeed
  name: pirateweather_api_test
  value_template: 'OK'