homeassistant: true

serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7c20c523ed12ec11ba4720c7bd930c07-if00-port0
frontend:
  port: 8099
  host: localhost
devices:
  '0xb4e3f9fffe7569c4':
    friendly_name: KP066
  '0x5c0272fffe40a9c7':
    friendly_name: KP067
    legacy: true
    debounce: 0
    filtered_attributes: []
    homeassistant: {}
    optimistic: true
